services:
  meilisearch:
    build:
      context: .
    ports:
      - "7700:7700"
    volumes:
      - 'meili_my:/meili_data'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s


volumes:
  meili_my:
    driver: local